name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ejecutar cuando haya un push a la rama `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # O la versión que estés usando

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build  # Asegúrate de que este comando esté en tu package.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.1
        with:
          branch: gh-pages  # El nombre de la rama donde se desplegará el contenido
          folder: dist      # La carpeta que contiene los archivos generados por Vite (por defecto es `dist`)
          token: ${{ secrets.GITHUB_TOKEN }}
