name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ejecutar cuando haya un push a la rama `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build 

      - name: Configure Git
        run: |
          git config --global user.email "pablo.ahumada1@mail.udp.cl"
          git config --global user.name "pixal-lab"
          git remote set-url origin https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}